# Generated by Django 2.0.1 on 2018-01-14 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Btc',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('txVolume', models.DecimalField(decimal_places=8, max_digits=50)),
                ('txCount', models.IntegerField()),
                ('marketCap', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=8, max_digits=20)),
                ('exchangeVolume', models.CharField(max_length=50)),
                ('generatedCoins', models.DecimalField(decimal_places=8, max_digits=50)),
                ('fees', models.DecimalField(decimal_places=8, max_digits=20)),
            ],
        ),
        migrations.CreateModel(
            name='Doge',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('txVolume', models.DecimalField(decimal_places=8, max_digits=50)),
                ('txCount', models.IntegerField()),
                ('marketCap', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=8, max_digits=20)),
                ('exchangeVolume', models.CharField(max_length=50)),
                ('generatedCoins', models.DecimalField(decimal_places=8, max_digits=50)),
                ('fees', models.DecimalField(decimal_places=8, max_digits=20)),
            ],
        ),
        migrations.CreateModel(
            name='Eth',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('txVolume', models.DecimalField(decimal_places=8, max_digits=50)),
                ('txCount', models.IntegerField()),
                ('marketCap', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=8, max_digits=20)),
                ('exchangeVolume', models.CharField(max_length=50)),
                ('generatedCoins', models.DecimalField(decimal_places=8, max_digits=50)),
                ('fees', models.DecimalField(decimal_places=8, max_digits=20)),
            ],
        ),
        migrations.CreateModel(
            name='Ltc',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('txVolume', models.DecimalField(decimal_places=8, max_digits=50)),
                ('txCount', models.IntegerField()),
                ('marketCap', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=8, max_digits=20)),
                ('exchangeVolume', models.CharField(max_length=50)),
                ('generatedCoins', models.DecimalField(decimal_places=8, max_digits=50)),
                ('fees', models.DecimalField(decimal_places=8, max_digits=20)),
            ],
        ),
    ]
