# Generated by Django 2.0.1 on 2018-01-14 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20180114_0746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='btc',
            name='date',
            field=models.DateField(),
        ),
    ]
