# Generated by Django 2.0.1 on 2018-01-14 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20180114_0811'),
    ]

    operations = [
        migrations.CreateModel(
            name='CryptoCurrency',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('currency_symbol', models.CharField(max_length=10)),
                ('currency_name', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('txVolume', models.DecimalField(decimal_places=8, max_digits=50)),
                ('price', models.DecimalField(decimal_places=8, max_digits=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Btc',
        ),
        migrations.DeleteModel(
            name='Doge',
        ),
        migrations.DeleteModel(
            name='Eth',
        ),
        migrations.DeleteModel(
            name='Ltc',
        ),
    ]
